import Landing from '@/components/Landing/Landing';
import ProjectStatus from '@/components/ProjectStatus/ProjectStatus';
import Results from '@/components/Results/Results';
import Head from 'next/head';

export default function ProjectDetails() {
  return (
    <>
      <Head>
        <title>Conservation Resources Hub - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
        <ProjectStatus />
        <Results />
      </main>
    </>
  );
}
